"PLCore::Bitset": Fixed MSVC error "error C2487: <x> : member of dll interface class may not be declared with dll interface" (had to change it in here because else, the virtual table couldn't be found when using GCC)